<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>preview</LangVersion>

    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>

    <!-- Assembly Info -->
    <RootNamespace>cc.isr.Iot.Tcp.Client.Ieee488</RootNamespace>
    <AssemblyName>cc.isr.Iot.Tcp.Client.Ieee488.MSTest</AssemblyName>

    <IsPackable>false</IsPackable>

  </PropertyGroup>

  <ItemGroup>
  </ItemGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);MYPROJREF;</DefineConstants>
  </PropertyGroup>

  <Choose>
    <When Condition="$(DefineConstants.Contains(';PROJREF;')) OR $(DefineConstants.Contains(';MYPROJREF;'))">
      <ItemGroup>
        <ProjectReference Include="..\client.ieee488\cc.isr.Iot.Tcp.Client.Ieee488.csproj" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <PackageReference Include="cc.isr.Iot.Tcp.Client.Ieee488" Version="1.0.0" />
      </ItemGroup>
    </Otherwise>
  </Choose>

  <Import Project="..\client.ieee488\version.build.props" />

</Project>
